# Generated by Django 2.1 on 2019-01-02 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('period', models.DurationField()),
                ('picture', models.ImageField(upload_to='images/')),
                ('pub_date', models.DateTimeField()),
                ('instructions', models.TextField()),
            ],
        ),
    ]
