# Generated by Django 2.1 on 2019-01-03 23:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('remindtowater', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plant',
            name='pub_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
