# Generated by Django 2.1 on 2019-01-03 23:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('remindtowater', '0002_auto_20190103_1506'),
    ]

    operations = [
        migrations.RenameField(
            model_name='plant',
            old_name='picture',
            new_name='image',
        ),
    ]
