# Generated by Django 2.1 on 2019-01-03 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('remindtowater', '0003_auto_20190103_1528'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plant',
            name='image',
            field=models.ImageField(default='images/None/no-img.jpg', null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='plant',
            name='instructions',
            field=models.TextField(null=True),
        ),
    ]
