# Generated by Django 2.1 on 2019-01-04 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('remindtowater', '0004_auto_20190103_1550'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plant',
            name='image',
            field=models.ImageField(default='images/None/no-img.jpg', upload_to='images/'),
        ),
    ]
