# Generated by Django 2.1 on 2019-01-06 22:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('remindtowater', '0007_plant_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plant',
            name='user',
        ),
    ]
